#define F(NAME,TARGET) class NAME { \
	allowedTargets = TARGET; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC HC_CL

class CfgRemoteExec {
	class Functions {
		mode = 1;
		jip = 1;
		
		#include "maverick\maverick_remoteExec_master.cpp"

		/* Client only functions */
		F(CL_fnc_AAN,CLIENT)
		F(CL_fnc_addVehicle2Chain,CLIENT)
		F(CL_fnc_adminid,CLIENT)
		F(CL_fnc_admininfo,CLIENT)
		F(CL_fnc_bountyReceive,CLIENT)
		F(CL_fnc_captureAlert,CLIENT)
		F(CL_fnc_captureCartelUpdate,CLIENT)
		F(CL_fnc_copLights,CLIENT)
		F(CL_fnc_copSearch,CLIENT)
		F(CL_fnc_copSiren,CLIENT)
		F(CL_fnc_copSiren2,CLIENT)
		F(CL_fnc_freezePlayer,CLIENT)
		F(CL_fnc_gangCreated,CLIENT)
		F(CL_fnc_gangDisbanded,CLIENT)
		F(CL_fnc_gangInvite,CLIENT)
		F(CL_fnc_garageRefund,CLIENT)
		F(CL_fnc_giveDiff,CLIENT)
		F(CL_fnc_hideObj,CLIENT)
		F(CL_fnc_impoundMenu,CLIENT)
		F(CL_fnc_jail,CLIENT)
		F(CL_fnc_jailMe,CLIENT)
		F(CL_fnc_knockedOut,CLIENT)
		F(CL_fnc_licenseCheck,CLIENT)
		F(CL_fnc_licensesRead,CLIENT)
		F(CL_fnc_copLicenseCheck,CLIENT)
		F(CL_fnc_copLicensesRead,CLIENT)
		F(CL_fnc_lightHouse,CLIENT)
		F(CL_fnc_mediclights,CLIENT)
		F(CL_fnc_medicRequest,CLIENT)
		F(CL_fnc_medicSiren,CLIENT)
		F(CL_fnc_moveIn,CLIENT)
		F(CL_fnc_pickupItem,CLIENT)
		F(CL_fnc_pickupMoney,CLIENT)
		F(CL_fnc_receiveItem,CLIENT)
		F(CL_fnc_receiveMoney,CLIENT)
		F(CL_fnc_copRemoveLicenses,CLIENT)
		F(CL_fnc_copGiveLicenses,CLIENT)
		F(CL_fnc_addLicenses,CLIENT)
		F(CL_fnc_removeLicenses,CLIENT)
		F(CL_fnc_restrain,CLIENT)
		F(CL_fnc_copRestrain,CLIENT)
		F(CL_fnc_revived,CLIENT)
		F(CL_fnc_robPerson,CLIENT)
		F(CL_fnc_robReceive,CLIENT)
		F(CL_fnc_searchClient,CLIENT)
		F(CL_fnc_seizeClient,CLIENT)
		F(CL_fnc_soundDevice,CLIENT)
		F(CL_fnc_spikeStripEffect,CLIENT)
		F(CL_fnc_tazeSound,CLIENT)
		F(CL_fnc_ticketPaid,CLIENT)
		F(CL_fnc_ticketPrompt,CLIENT)
		F(CL_fnc_vehicleAnimate,CLIENT)
		F(CL_fnc_wantedList,CLIENT)
		F(CL_fnc_wireTransfer,CLIENT)
		F(SOCK_fnc_dataQuery,CLIENT)
		F(SOCK_fnc_insertPlayerInfo,CLIENT)
		F(SOCK_fnc_requestReceived,CLIENT)
		F(SOCK_fnc_updateRequest,CLIENT)
		F(TON_fnc_clientGangKick,CLIENT)
		F(TON_fnc_clientGangLeader,CLIENT)
		F(TON_fnc_clientGangLeft,CLIENT)
		F(TON_fnc_clientGetKey,CLIENT)
		F(TON_fnc_clientMessage,CLIENT)
		F(TON_fnc_player_query,CLIENT)
		F(CL_fnc_vehicleEmpd,CLIENT)
		F(CL_fnc_vehicleWarned,CLIENT)
		F(CL_fnc_carAlarmSound,CLIENT)
		F(CL_fnc_hasOrgan,CLIENT)
		F(CL_fnc_hasFlesh,CLIENT)
		F(CL_fnc_empGrenade,CLIENT)
		F(CL_fnc_smartphone,CLIENT)
		F(CL_fnc_markers,CLIENT)
		F(CL_fnc_tieing,CLIENT)
		F(CL_fnc_tieingb,CLIENT)
		F(CL_fnc_gagged,CLIENT)
		
		/* Server only functions */
		F(bis_fnc_execvm,SERVER)
		F(DB_fnc_insertRequest,SERVER)
		F(DB_fnc_queryRequest,SERVER)
		F(DB_fnc_updatePartial,SERVER)
		F(DB_fnc_updateRequest,SERVER)
		F(CL_fnc_jailSys,SERVER)
		F(CL_fnc_wantedAdd,SERVER)
		F(CL_fnc_wantedBounty,SERVER)
		F(CL_fnc_wantedCrimes,SERVER)
		F(CL_fnc_wantedFetch,SERVER)
		F(CL_fnc_wantedProfUpdate,SERVER)
		F(CL_fnc_wantedRemove,SERVER)
		F(TON_fnc_addContainer,SERVER)
		F(TON_fnc_addHouse,SERVER)
		F(TON_fnc_chopShopSell,SERVER)
		F(TON_fnc_chopShopClaim,SERVER)
		F(TON_fnc_cleanupRequest,SERVER)
		F(TON_fnc_deleteDBContainer,SERVER)
		F(TON_fnc_getID,SERVER)
		F(TON_fnc_getVehicles,SERVER)
		F(TON_fnc_insertGang,SERVER)
		F(TON_fnc_keyManagement,SERVER)
//		F(TON_fnc_managesc,SERVER)
		F(TON_fnc_pickupAction,SERVER)
		F(TON_fnc_removeGang,SERVER)
		F(TON_fnc_sellHouse,SERVER)
		F(TON_fnc_sellHouseContainer,SERVER)
		F(TON_fnc_setObjVar,SERVER)
		F(TON_fnc_spawnVehicle,SERVER)
		F(TON_fnc_spikeStrip,SERVER)
		F(TON_fnc_updateGang,SERVER)
		F(TON_fnc_updateHouseContainers,SERVER)
		F(TON_fnc_updateHouseTrunk,SERVER)
		F(TON_fnc_vehicleCreate,SERVER)
		F(TON_fnc_vehicleDelete,SERVER)
		F(TON_fnc_vehicleStore,SERVER)
		F(TON_fnc_vehicleUpdate,SERVER)
		F(TON_fnc_vehicleCrush,SERVER)
		F(TON_fnc_handleBlastingCharge,SERVER)
		F(TON_fnc_vAH_update,SERVER)
		F(TON_fnc_msgRequest,SERVER)
		F(TON_fnc_cleanupMessages,SERVER)
		F(A3Log,SERVER)
		F(TON_fnc_generateAirdrop,SERVER)

		/* HeadlessClient only functions */
		F(HC_fnc_addContainer,HC)
		F(HC_fnc_addHouse,HC)
		F(HC_fnc_chopShopSell,HC)
		F(HC_fnc_deleteDBContainer,HC)
		F(HC_fnc_getVehicles,HC)
		F(HC_fnc_insertGang,HC)
		F(HC_fnc_insertRequest,HC)
		F(HC_fnc_insertVehicle,HC)
		F(HC_fnc_jailSys,HC)
		F(HC_fnc_keyManagement,HC)
		F(HC_fnc_queryRequest,HC)
		F(HC_fnc_removeGang,HC)
		F(HC_fnc_sellHouse,HC)
		F(HC_fnc_sellHouseContainer,HC)
		F(HC_fnc_spawnVehicle,HC)
		F(HC_fnc_spikeStrip,HC)
		F(HC_fnc_updateGang,HC)
		F(HC_fnc_updateHouseContainers,HC)
		F(HC_fnc_updateHouseTrunk,HC)
		F(HC_fnc_updatePartial,HC)
		F(HC_fnc_updateRequest,HC)
		F(HC_fnc_vehicleCreate,HC)
		F(HC_fnc_vehicleDelete,HC)
		F(HC_fnc_vehicleStore,HC)
		F(HC_fnc_vehicleUpdate,HC)
		F(HC_fnc_wantedAdd,HC)
		F(HC_fnc_wantedBounty,HC)
		F(HC_fnc_wantedCrimes,HC)
		F(HC_fnc_wantedFetch,HC)
		F(HC_fnc_wantedProfUpdate,HC)
		F(HC_fnc_wantedRemove,HC)
		F(HC_fnc_chopShopClaim,HC)
		F(HC_fnc_vehicleCrush,HC)

		/* Functions for everyone */
        F(BIS_fnc_effectKilledAirDestruction,ANYONE)
        F(BIS_fnc_effectKilledSecondaries,ANYONE)
		F(CL_fnc_animSync,ANYONE)
		F(CL_fnc_broadcast,ANYONE)
		F(CL_fnc_colorVehicle,ANYONE)
		F(CL_fnc_corpse,ANYONE)
		F(CL_fnc_demoChargeTimer,ANYONE)
		F(CL_fnc_flashbang,ANYONE)
		F(CL_fnc_jumpFnc,ANYONE)
		F(CL_fnc_lockVehicle,ANYONE)
		F(CL_fnc_pulloutVeh,ANYONE)
		F(CL_fnc_pushFunction,ANYONE)
		F(CL_fnc_say3D,ANYONE)
		F(CL_fnc_setFuel,ANYONE)
		F(CL_fnc_simDisable,ANYONE)
		F(CL_fnc_vAH_reciever,ANYONE)
		F(CL_fnc_setDamage,ANYONE)
	};

	class Commands {
		mode = 1;
		jip = 0;
		F(call,ANYONE)
		F(addHandgunItem,ANYONE)
		F(addMagazine,ANYONE)
		F(addPrimaryWeaponItem,ANYONE)
		F(addWeapon,ANYONE)
		F(setFuel,ANYONE)
	};
};
